blueprint:
  name: Occupancy Based States Toggle
  description: Turn off Target Entities when area becomes empty. When occupancy is detected set Target Entities back to their previous states. Original states are remembered for a specified time, after that Default Actions are ran on the event of occupancy.
  domain: automation
  input:
    scene_name:
      name: Scene Name
      description: Any unique name to store a scene with original states
      selector:
        text:
    occupancy_sensor:
      name: Occupancy Sensor
      description: Occupancy sensor to use for this automation
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    target_entities:
      name: Target Entities
      description: List of entities to control by this automation
      selector:
        entity:
          domain:
            - light
            - switch
            - cover
            - media_player
            - climate
            - fan
            - humidifier
          multiple: true
    turn_off_after:
      name: Turn Off After
      description: Time to wait before turning off entities
      default:
        seconds: 0
      selector:
        duration:
    remember_for:
      name: Remember States For
      description: Time required to forget previous states and fallback to Default Actions
      default:
        hours: 1
      selector:
        duration:
    default_actions:
      name: Default Actions
      description: Default actions on the event of occupancy, if original states are forgotten
      default: []
      selector:
        action:
    condition_template:
      name: Condition Template
      description: Template that specifies condition to run this automation under
      default: "True"
      selector:
        template:

variables:
  _scene_name: !input scene_name
  scene_id: "{{ _scene_name | slugify }}"
  entities_all: !input target_entities
  entities_light: "{{ entities_all | select('match', 'light') | list }}"
  entities_switch: "{{ entities_all | select('match', 'switch') | list }}"
  entities_cover: "{{ entities_all | select('match', 'cover') | list }}"
  entities_media_player: "{{ entities_all | select('match', 'media_player') | list }}"
  entities_climate: "{{ entities_all | select('match', 'climate') | list }}"
  entities_fan: "{{ entities_all | select('match', 'fan') | list }}"
  entities_humidifier: "{{ entities_all | select('match', 'humidifier') | list }}"

trigger:
  - platform: state
    entity_id: !input occupancy_sensor
    to: "on"
    id: OCCUPIED
  - platform: state
    entity_id: !input occupancy_sensor
    to: "off"
    id: EMPTY
    for: !input turn_off_after
  - platform: state
    entity_id: !input occupancy_sensor
    to: "off"
    id: EMPTY_TIMEOUT
    for: !input remember_for

condition:
  - condition: template
    value_template: !input condition_template

mode: single
action:
  - choose:
      - conditions:
          - condition: trigger
            id: OCCUPIED
        sequence:
          - service: scene.turn_on
            data:
              entity_id: "scene.{{ scene_id }}"
      - conditions:
          - condition: trigger
            id: EMPTY
        sequence:
          - service: scene.create
            data:
              scene_id: "{{ scene_id }}"
              snapshot_entities: "{{ entities_all }}"
          - service: light.turn_off
            target:
              entity_id: "{{ entities_light }}"
          - service: switch.turn_off
            target:
              entity_id: "{{ entities_switch }}"
          - service: cover.close_cover
            target:
              entity_id: "{{ entities_cover }}"
          - service: media_player.turn_off
            target:
              entity_id: "{{ entities_media_player }}"
          - service: climate.turn_off
            target:
              entity_id: "{{ entities_climate }}"
          - service: fan.turn_off
            target:
              entity_id: "{{ entities_fan }}"
          - service: humidifier.turn_off
            target:
              entity_id: "{{ entities_humidifier }}"
      - conditions:
          - condition: trigger
            id: EMPTY_TIMEOUT
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input occupancy_sensor
                to: "on"
            continue_on_timeout: false
          - if:
              - condition: template
                value_template: "True"
            then: !input default_actions
